# Homework Assignment 2

In [2]:
import numpy as np
import pandas as pd

### Question 1

Create a 4x3 array of letters from `a` through `l` and call it `array1`. Copy the array and call it `array2`, then reshape `array2` to a 6x2 array. Create another copy of the array, called `array3`, and flatten it into a one-dimensional array. Print all three arrays.

In [4]:
array1 = np.array([['a','b','c'],['d','e','f'],['g','h','i'],['j','k','l']])
print('The 4x3 array is:\n',array1)
array2 = array1.copy()
array2 = array2.reshape(6,2)
print('The 6x2 array is:\n',array2)
array3 = array1.copy()
array3 = array3.flatten()
print('The flattened array is:\n',array3)

The 4x3 array is:
 [['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']
 ['j' 'k' 'l']]
The 6x2 array is:
 [['a' 'b']
 ['c' 'd']
 ['e' 'f']
 ['g' 'h']
 ['i' 'j']
 ['k' 'l']]
The flattened array is:
 ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l']


### Question 2

Create a 3x3 array of integers from 1-9. Calculate the array's row means, then broadcast the row means to subtract them from the original array. (**Note:** the row axis in Python is denoted by `0` while the column axis is denoted by `1`.)

In [6]:
array_new = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('The array is:\n',array_new)
row_mean = array_new.mean(0)
print('The row mean of the array is:\n',row_mean)
array_new = array_new - row_mean
print('The subtracted array is:\n',array_new)

The array is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The row mean of the array is:
 [4. 5. 6.]
The subtracted array is:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


### Question 3

Using the two arrays provided, first select all rows from `grades` where `students` is either `'Cora'` or `'David'`

In [27]:
students = np.array(['Arthur', 'Betty', 'Cora', 'David', 'Ethan'])
grades = np.array([[95, 80], [72, 78], [85, 85], [87, 92], [82, 88]])
print('The grades of Cora is:',grades[students == 'Cora'])
print('The grades of David is:',grades[students == 'David'])

The grades of Cora is: [[85 85]]
The grades of David is: [[87 92]]


### Question 4

Use `np.where()` to create a Boolean array that will print `True` when the student's grade is greater than the overall class average (or `mean`) and `False` when it is not.

In [30]:
Boolean_array = np.where(grades > grades.mean(0),True,False)
print(Boolean_array)        

[[ True False]
 [False False]
 [ True  True]
 [ True  True]
 [False  True]]


### Question 5

Create a 2x4 array of random numbers called `a` using `np.random.randn()` and a 3x4 array of random numbers called `b`. Multiply matrices `a` and `b` together to find the dot product. What is the `shape` of the resulting array? (**Note:** Remember to transpose the arrays as needed!)

In [46]:
a = np.random.randn(2,4)
print ('Matrix a:\n',a)
b = np.random.randn(3,4)
print('Matrix b:\n',b)
b = b.T
print('Transposed matrix b:\n',b)
c = np.dot(a,b)
print('The dot product matrix of the matrices a and b is:\n',c)
print('The shape of the dot product matrix of the matrices a and b is is:', np.shape(c))

Matrix a:
 [[-0.5154657  -0.60380208  1.73738739  0.31027445]
 [-1.02804125  1.02062999  1.86328432  0.64486013]]
Matrix b:
 [[-0.84443452  0.98555164 -0.7969549   1.56531933]
 [ 1.18889847  0.09403536  0.80366074 -0.70719386]
 [-0.18221092  0.60667817 -0.87734409 -0.08656151]]
Transposed matrix b:
 [[-0.84443452  1.18889847 -0.18221092]
 [ 0.98555164  0.09403536  0.60667817]
 [-0.7969549   0.80366074 -0.87734409]
 [ 1.56531933 -0.70719386 -0.08656151]]
The dot product matrix of the matrices a and b is:
 [[-1.0587419   0.50723072 -1.82353445]
 [ 1.39845553 -0.08485403 -0.88404729]]
The shape of the dot product matrix of the matrices a and b is is: (2, 3)


### Question 6

Create a Pandas `Series` using the given list of U.S. presidents as the values and the list of election years as the index. Who was elected president in 1876?

In [59]:
year = [1788,1792,1796,1800,1804,1808,1812,1816,1820,1824,1828,1832,1836,1840,1840,1844,1848,1848,1852,1856,1860,1864,1864,1868,1872,1876,1880,1880,1884,1888,1892,1896,1900,1904,1908,1912,1916,1920,1924,1928,1932,1936,1940,1944,1948,1952,1956,1960,1964,1968,1972,1972,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020]
name = ['George Washington','George Washington','John Adams','Thomas Jefferson','Thomas Jefferson','James Madison','James Madison','James Monroe','James Monroe','John Quincy Adams','Andrew Jackson','Andrew Jackson','Martin Van Buren','William Henry Harrison','John Tyler','James K. Polk','Zachary Taylor','Millard Fillmore','Franklin Pierce','James Buchanan','Abraham Lincoln','Abraham Lincoln','Andrew Johnson','Ulysses S. Grant','Ulysses S. Grant','Rutherford B. Hayes','James A. Garfield','Chester A. Arthur','Grover Cleveland','Benjamin Harrison','Grover Cleveland','William McKinley','William McKinley','Theodore Roosevelt','William Howard Taft','Woodrow Wilson','Woodrow Wilson','Warren G. Harding','Calvin Coolidge','Herbert Hoover','Franklin D. Roosevelt','Franklin D. Roosevelt','Franklin D. Roosevelt','Franklin D. Roosevelt','Harry S. Truman','Dwight D. Eisenhower','Dwight D. Eisenhower','John F. Kennedy','Lyndon B. Johnson','Richard Nixon','Richard Nixon','Gerald Ford','Jimmy Carter','Ronald Reagan','Ronald Reagan','George H. W. Bush','Bill Clinton','Bill Clinton','George W. Bush','George W. Bush','Barack Obama','Barack Obama','Donald Trump','Joe Biden']
series1 = pd.Series(data = name, index = year)
print('The president of U.S. elected in 1876 is:',series1[1876])

The president of U.S. elected in 1876 is: Rutherford B. Hayes


### Question 7

Create a Pandas DataFrame called `df` from the three Series below. Use the Series names as the column names. Slice the DataFrame to see what `party` William Howard Taft belonged to and what `year` he was elected.

In [73]:
year = pd.Series([1788,1792,1796,1800,1804,1808,1812,1816,1820,1824,1828,1832,1836,1840,1840,1844,1848,1848,1852,1856,1860,1864,1864,1868,1872,1876,1880,1880,1884,1888,1892,1896,1900,1904,1908,1912,1916,1920,1924,1928,1932,1936,1940,1944,1948,1952,1956,1960,1964,1968,1972,1972,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020])
name = pd.Series(['George Washington','George Washington','John Adams','Thomas Jefferson','Thomas Jefferson','James Madison','James Madison','James Monroe','James Monroe','John Quincy Adams','Andrew Jackson','Andrew Jackson','Martin Van Buren','William Henry Harrison','John Tyler','James K. Polk','Zachary Taylor','Millard Fillmore','Franklin Pierce','James Buchanan','Abraham Lincoln','Abraham Lincoln','Andrew Johnson','Ulysses S. Grant','Ulysses S. Grant','Rutherford B. Hayes','James A. Garfield','Chester A. Arthur','Grover Cleveland','Benjamin Harrison','Grover Cleveland','William McKinley','William McKinley','Theodore Roosevelt','William Howard Taft','Woodrow Wilson','Woodrow Wilson','Warren G. Harding','Calvin Coolidge','Herbert Hoover','Franklin D. Roosevelt','Franklin D. Roosevelt','Franklin D. Roosevelt','Franklin D. Roosevelt','Harry S. Truman','Dwight D. Eisenhower','Dwight D. Eisenhower','John F. Kennedy','Lyndon B. Johnson','Richard Nixon','Richard Nixon','Gerald Ford','Jimmy Carter','Ronald Reagan','Ronald Reagan','George H. W. Bush','Bill Clinton','Bill Clinton','George W. Bush','George W. Bush','Barack Obama','Barack Obama','Donald Trump','Joe Biden'])
party = pd.Series(['Unaffiliated','Unaffiliated','Federalist','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic','Democratic','Democratic','Whig','Whig','Democratic','Whig','Whig','Democratic','Democratic','Republican','National Union','Democratic','Republican','Republican','Republican','Republican','Republican','Democratic','Republican','Democratic','Republican','Republican','Republican','Republican','Democratic','Democratic','Republican','Republican','Republican','Democratic','Democratic','Democratic','Democratic','Democratic','Republican','Republican','Democratic','Democratic','Republican','Republican','Republican','Democratic','Republican','Republican','Republican','Democratic','Democratic','Republican','Republican','Democratic','Democratic','Republican','Democratic'])
number = pd.Series([1,1,2,3,3,4,4,5,5,6,7,7,8,9,10,11,12,13,14,15,16,16,17,18,18,19,20,21,22,23,24,25,25,26,27,28,28,29,30,31,32,32,32,32,33,34,34,35,36,37,37,38,39,40,40,41,42,42,43,43,44,44,45,46])
df = pd.DataFrame({'Number':number,'Year': year,'Name': name, 'Party': party})
print('The details of what party and year William Howard Taft was elected is:\n',df[df.Name=='William Howard Taft'])

The details of what party and year William Howard Taft was elected is:
     Number  Year                 Name       Party
34      27  1908  William Howard Taft  Republican


### Question 8

Using the DataFrame you created in the question before, `set_index` to the `year` column if you have not already done this. Slice the DataFrame using `.loc` to show all those who were president from 1900-1920.

In [79]:
df = df.set_index(year)
df_part = df.loc[1900:1920]
print(df_part)

      Number  Year                 Name       Party
1900      25  1900     William McKinley  Republican
1904      26  1904   Theodore Roosevelt  Republican
1908      27  1908  William Howard Taft  Republican
1912      28  1912       Woodrow Wilson  Democratic
1916      28  1916       Woodrow Wilson  Democratic
1920      29  1920    Warren G. Harding  Republican


### Question 9

Filter the DataFrame you created in Question 7 to see how many `'Democratic'` and how many `'Republican'` presidents we have had. Use the `.count()` method to count the number of rows in each category and `print` the name of the party along with the result.

In [100]:
Dem = 'Democratic'
print('The count of {}:'.format(Dem),(df[df.Party == 'Democratic'].Number).count())
Rep = 'Republican'
print('The count of {}:'.format(Rep),(df[df.Party == 'Republican'].Number).count())  
        

The count of Democratic: 24
The count of Republican: 25


### Question 10

`Map` a `lambda` function onto the `'name'` column to capitalize all the president names in the DataFrame you created in Question 7. Remember to apply the `.upper()` method to capitalize the letters.

In [104]:
df['Name'] = df['Name'].map(lambda x: x.upper())
df['Name']

1788    GEORGE WASHINGTON
1792    GEORGE WASHINGTON
1796           JOHN ADAMS
1800     THOMAS JEFFERSON
1804     THOMAS JEFFERSON
              ...        
2004       GEORGE W. BUSH
2008         BARACK OBAMA
2012         BARACK OBAMA
2016         DONALD TRUMP
2020            JOE BIDEN
Name: Name, Length: 64, dtype: object